### ISSUE TITLE
Cannot Read property "_hasFake" of undefined

### ISSUE THREAD

**Issue by ShaunWMusic** [poppinss/adonis-fold#10]
I am migrating from Adonis 3.2 to Adonis 4.0. While trying to connect using JWT auth token I received this error. I'm open to the idea of it being an operator error, but any enlightenment would be much appreciated at this point. 

`node_modules/@adonisjs/fold/src/Ioc/index.js:712:14`
Cannot Read property "_hasFake" of undefined
<img width="1519" alt="screen shot 2018-02-01 at 1 04 50 pm" src="https://user-images.githubusercontent.com/16964213/35697753-bd580e90-0750-11e8-81e0-944238615dc5.png">

**Comment by thetutlage** [comment]
Can u share how exactly you are trying to upgrade from 3.2 to 4.0.

1. Did you created a new 4.0 app and moving your code to it?
2. Can you share some code exactly where you receive this error.

**Comment by shaunwillis-SpectrumReach** [comment]
I did create a new 4.0 app and I'm in the middle of moving my code over to it. My issue is that I was using ryan tablada's https://www.npmjs.com/package/adonis-jsonapi api package in our current 3.2 won't work for 4.0. 

I'm attempting to update ryan tablada's json-api package from 3.2 to 4.0. but when i pull it in to my adonis 4.0 package it gives me this error when I run a get request. 

is it an issue with namespace? I've combed through the adonis docs where you talk about the changes that were made in 3.2. 

Here is the json-api package that i'm working on that isn't working well with adonis-fold. 
https://www.npmjs.com/package/adonis4-jsonapi

**Comment by shaunwillis-SpectrumReach** [comment]
sorry if i confused you with the previous comment.. i have two github accounts, and i'm updating this json-api package for the company I work for Spectrum Reach to use this.

**Comment by shaunwillis-SpectrumReach** [comment]
`'use strict';

const JsonApiSerializer = require('jsonapi-serializer').Serializer;
const { JsonApiRequest, JsonApiError, ValidationError } = require('./JsonApiRequest');

function setupSerializer(use) {
  return function (serializerName, data, meta) {
    const helpers = use('Helpers');

    const View = use(helpers.makeNameSpace('App/Controllers/Http/JsonApiViews', serializerName));
    const view = new View(use);

    if (data.toJSON && typeof data.toJSON === 'function') {
      data = data.toJSON();
    }

    const pluralizeType = Array.isArray(data);

    const options = Object.assign({}, view.build({ meta: meta }), { pluralizeType });

    const json = new JsonApiSerializer(view.type, options).serialize(data);

    return json;
  };
}

class JsonApi {

  constructor(use) {
    const Response = use('@adonisjs/framework/Src/Response');
    const serializer = setupSerializer(use);

    Response.macro('serializePayload', serializer);
    Response.macro('jsonApi', function (serializerName, data, meta = {}, statusCode = 200) {
      const json = serializer(serializerName, data, meta);

      this.status(statusCode).json(json);
    });

    Response.macro('isJsonApiError', (err) => err instanceof JsonApiError);
    Response.macro('isValidationError', (err) => err instanceof ValidationError);
    Response.macro('jsonApiError', function (err) {
      if (err instanceof ValidationError) {
        this.status(err.status).json({ errors: err.makeErrors() });
      } else if (err instanceof JsonApiError) {
        this.status(err.status).json({ errors: [err.message] });
      } else {
        this.status(err.status).json({ errors: [{
          status: err.status,
          title: err.name,
          detail: err.message,
        }] });
      }
    });
  }

  async handle({request, response, next}) => {
    request.jsonApi = new JsonApiRequest(request);

    await next;
  }

}

module.exports = JsonApi;
`

**Comment by shaunwillis-SpectrumReach** [comment]
does any of this code look janky to you? I have JsonApiSerializer in there from the previous version, but I thought I read in the docs that the syntax needs to be updated for the new namespace.

**Comment by thetutlage** [comment]
Closed for house keeping purposes. Re-open if problem still persists
