### ISSUE TITLE
Please publish package 4.0.9 in npm repository, because of last available has 3.0.3

### ISSUE THREAD

**Issue by gustawdaniel** [poppinss/adonis-fold#15]
In maser I can see 

```
  "version": "4.0.9",
```

but on npm page

> https://www.npmjs.com/package/adonis-fold

```
3.0.3 • Public • Published 2 years ago
```

Please update it. It is related with the following dependencies tree

```
├─┬ adonis-cli@2.1.9
│ └─┬ adonis-fold@3.0.3
│   └─┬ coveralls@2.13.3
│     └─┬ request@2.79.0
│       └─┬ hawk@3.1.3
│         ├─┬ boom@2.10.1
│         │ └── hoek@2.16.3  deduped
│         ├── hoek@2.16.3 
│         └─┬ sntp@1.0.9
│           └── hoek@2.16.3  deduped
```

But these old packages has problems with `npm audit security report` and now are updated.

In your master I can see you require

```
    "coveralls": "^3.0.2",
```

So only publication in `npm` is required to fix it.

**Comment by thetutlage** [comment]
You are on a way older version of Adonis. The newest one's are scoped under `@adonisjs` namespace. https://www.npmjs.com/package/@adonisjs/fold
