### ISSUE TITLE
Cannot use with symbolic links/npm link

### ISSUE THREAD

**Issue by andruu** [poppinss/adonis-fold#3]
When developing services locally it would be useful to use the `npm link` command to create local npm modules.

Inside of the use method it's looking for a type (`Ioc._type(namespace)`) which is always being returned as undefined. It works fine if the service provider lives inside of the node_modules directory though.

**Comment by andruu** [comment]
1) The service provider is in the application, although the service is in another module.
2) Registering under bootstrap/app.js the same way the adonis-framework services are loaded.

So let's say I have an application /adonis-application and a service /service and in /adonis-application/bootstrap/app.js I register `'service/providers/ServiceProvider'`. In the bootstrap/http.js it's calling the /adonis-application/node_modules/adonis-fold/src/Registrar/index.js but it's using the IoC container at /service/node_modules/src/Ioc/index.js.

**Comment by thetutlage** [comment]
@andruu Do not keep your providers inside `app` directory, that is booked for autoloading. There is a `providers` directory in the root of the application. Consider creating the provider there.

So let's say you create a provider called FooProvider. It will under `providers/FooProvider.js` and you are supposed to register it inside the `bootstrap/app.js` file.

#### bootstrap/app.js
```javascript

const path = require('path')

const providers = [
   path.join(__dirname, '../providers/FooProvider')
]
```

**Comment by andruu** [comment]
@thetutlage they are under the providers directory. I'll create an example shortly demonstrating my issue. Might be something I'm overlooking.

**Comment by andruu** [comment]
@thetutlage Here is an example using a brand new install of 3.0 with the validation service provider checked out from master.

https://github.com/andruu/adonistest

**Comment by thetutlage** [comment]
Nice let me check

**Comment by thetutlage** [comment]
@andruu This is the issue at `npm` level. AdonisJs has a peer dependency on `adonis-fold` and symlinks does not play well with `peer-dependencies`. Here are some related issues.

https://github.com/npm/npm/issues/5875
https://github.com/npm/npm/issues/5080

**Comment by andruu** [comment]
Got it, thanks for looking into it.
